services:
  devicemanager.api:
    image: devicemanager.api
    container_name: devicemanager.api
    build:
      context: .
      dockerfile: DeviceManager.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=DeviceManagerDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      - JWT_KEY=${JWT_KEY}
    depends_on:
      sqlserver:
        condition: service_healthy
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: device-manager-db
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - device-manager-db-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q 'SELECT 1' -No"]
      interval: 10s
      timeout: 5s
      retries: 8
      start_period: 20s

volumes:
  device-manager-db-data: