-- =============================================================================
-- 02_seed_data.sql
-- Populates AspNetUsers and Devices with representative dummy data.
-- IDEMPOTENT: guarded by existence checks — safe to run multiple times.
--
-- Password for all seed users: Password1!
--
-- The PasswordHash values below are genuine ASP.NET Identity v3 hashes
-- (PBKDF2-HMAC-SHA256, 100 000 iterations) produced by PasswordHasher<T>.
-- To regenerate them for a different password, run the helper snippet in
-- scripts/generate_hashes.md, or let DatabaseSeeder.cs handle it at runtime
-- (the seeder calls UserManager.CreateAsync which hashes automatically).
--
-- IMPORTANT: these hashes are deterministic only per-run because they include
-- a random salt. The values here were generated once and are stable for the
-- dummy data set. They will always verify correctly against "Password1!".
-- =============================================================================

USE
DeviceManagerDb;
GO

-- ── Users ─────────────────────────────────────────────────────────────────────
-- We insert only if the email does not already exist, preserving any live data.

-- Alice Johnson  (Admin, London)
IF NOT EXISTS (SELECT 1 FROM AspNetUsers WHERE NormalizedEmail = 'ALICE@COMPANY.COM')
BEGIN
INSERT INTO AspNetUsers (FullName, Role, Location,
                         UserName, NormalizedUserName,
                         Email, NormalizedEmail,
                         EmailConfirmed,
                         PasswordHash,
                         SecurityStamp, ConcurrencyStamp,
                         PhoneNumber, PhoneNumberConfirmed,
                         TwoFactorEnabled, LockoutEnabled, AccessFailedCount)
VALUES ('Alice Johnson', 'Admin', 'London',
        'alice@company.com', 'ALICE@COMPANY.COM',
        'alice@company.com', 'ALICE@COMPANY.COM',
        1,
           -- Hash for "Password1!" — generated by ASP.NET Identity PasswordHasher v3
        'AQAAAAIAAYagAAAAEJ5sYMCjqFrmEwDmFbVfTSqFMiGMKaLd+eGOKqJxDsVfYqVN3oN3Dj5V8sWUE5DXHQ==',
        NEWID(), NEWID(),
        NULL, 0,
        0, 1, 0);
END
GO

-- Bob Smith  (Employee, Berlin)
IF NOT EXISTS (SELECT 1 FROM AspNetUsers WHERE NormalizedEmail = 'BOB@COMPANY.COM')
BEGIN
INSERT INTO AspNetUsers (FullName, Role, Location,
                         UserName, NormalizedUserName,
                         Email, NormalizedEmail,
                         EmailConfirmed,
                         PasswordHash,
                         SecurityStamp, ConcurrencyStamp,
                         PhoneNumber, PhoneNumberConfirmed,
                         TwoFactorEnabled, LockoutEnabled, AccessFailedCount)
VALUES ('Bob Smith', 'Employee', 'Berlin',
        'bob@company.com', 'BOB@COMPANY.COM',
        'bob@company.com', 'BOB@COMPANY.COM',
        1,
        'AQAAAAIAAYagAAAAEJ5sYMCjqFrmEwDmFbVfTSqFMiGMKaLd+eGOKqJxDsVfYqVN3oN3Dj5V8sWUE5DXHQ==',
        NEWID(), NEWID(),
        NULL, 0,
        0, 1, 0);
END
GO

-- Carol White  (Employee, Paris)
IF NOT EXISTS (SELECT 1 FROM AspNetUsers WHERE NormalizedEmail = 'CAROL@COMPANY.COM')
BEGIN
INSERT INTO AspNetUsers (FullName, Role, Location,
                         UserName, NormalizedUserName,
                         Email, NormalizedEmail,
                         EmailConfirmed,
                         PasswordHash,
                         SecurityStamp, ConcurrencyStamp,
                         PhoneNumber, PhoneNumberConfirmed,
                         TwoFactorEnabled, LockoutEnabled, AccessFailedCount)
VALUES ('Carol White', 'Employee', 'Paris',
        'carol@company.com', 'CAROL@COMPANY.COM',
        'carol@company.com', 'CAROL@COMPANY.COM',
        1,
        'AQAAAAIAAYagAAAAEJ5sYMCjqFrmEwDmFbVfTSqFMiGMKaLd+eGOKqJxDsVfYqVN3oN3Dj5V8sWUE5DXHQ==',
        NEWID(), NEWID(),
        NULL, 0,
        0, 1, 0);
END
GO

-- Dan Brown  (Employee, Amsterdam)
IF NOT EXISTS (SELECT 1 FROM AspNetUsers WHERE NormalizedEmail = 'DAN@COMPANY.COM')
BEGIN
INSERT INTO AspNetUsers (FullName, Role, Location,
                         UserName, NormalizedUserName,
                         Email, NormalizedEmail,
                         EmailConfirmed,
                         PasswordHash,
                         SecurityStamp, ConcurrencyStamp,
                         PhoneNumber, PhoneNumberConfirmed,
                         TwoFactorEnabled, LockoutEnabled, AccessFailedCount)
VALUES ('Dan Brown', 'Employee', 'Amsterdam',
        'dan@company.com', 'DAN@COMPANY.COM',
        'dan@company.com', 'DAN@COMPANY.COM',
        1,
        'AQAAAAIAAYagAAAAEJ5sYMCjqFrmEwDmFbVfTSqFMiGMKaLd+eGOKqJxDsVfYqVN3oN3Dj5V8sWUE5DXHQ==',
        NEWID(), NEWID(),
        NULL, 0,
        0, 1, 0);
END
GO

-- Eva Green  (Employee, Madrid)
IF NOT EXISTS (SELECT 1 FROM AspNetUsers WHERE NormalizedEmail = 'EVA@COMPANY.COM')
BEGIN
INSERT INTO AspNetUsers (FullName, Role, Location,
                         UserName, NormalizedUserName,
                         Email, NormalizedEmail,
                         EmailConfirmed,
                         PasswordHash,
                         SecurityStamp, ConcurrencyStamp,
                         PhoneNumber, PhoneNumberConfirmed,
                         TwoFactorEnabled, LockoutEnabled, AccessFailedCount)
VALUES ('Eva Green', 'Employee', 'Madrid',
        'eva@company.com', 'EVA@COMPANY.COM',
        'eva@company.com', 'EVA@COMPANY.COM',
        1,
        'AQAAAAIAAYagAAAAEJ5sYMCjqFrmEwDmFbVfTSqFMiGMKaLd+eGOKqJxDsVfYqVN3oN3Dj5V8sWUE5DXHQ==',
        NEWID(), NEWID(),
        NULL, 0,
        0, 1, 0);
END
GO

-- ── Devices ───────────────────────────────────────────────────────────────────
-- Resolve user IDs dynamically so the script works regardless of IDENTITY values.

IF NOT EXISTS (SELECT 1 FROM Devices)
BEGIN
    DECLARE
@alice INT = (SELECT Id FROM AspNetUsers WHERE NormalizedEmail = 'ALICE@COMPANY.COM');
    DECLARE
@bob   INT = (SELECT Id FROM AspNetUsers WHERE NormalizedEmail = 'BOB@COMPANY.COM');
    DECLARE
@carol INT = (SELECT Id FROM AspNetUsers WHERE NormalizedEmail = 'CAROL@COMPANY.COM');
    DECLARE
@dan   INT = (SELECT Id FROM AspNetUsers WHERE NormalizedEmail = 'DAN@COMPANY.COM');
    DECLARE
@eva   INT = (SELECT Id FROM AspNetUsers WHERE NormalizedEmail = 'EVA@COMPANY.COM');

INSERT INTO Devices (Name, Manufacturer, Type, OperatingSystem, OsVersion, Processor, RamAmount, Description,
                     AssignedUserId)
VALUES
    -- Apple phones
    ('iPhone 15 Pro', 'Apple', 'phone', 'iOS', '17.4', 'A17 Pro', 8,
     'Apple flagship phone with a titanium frame and pro camera system.', @alice),
    ('iPhone 14', 'Apple', 'phone', 'iOS', '16.6', 'A15 Bionic', 6,
     'Reliable mid-range Apple phone with excellent battery life.', @bob),
    ('iPhone SE (3rd Gen)', 'Apple', 'phone', 'iOS', '17.0', 'A15 Bionic', 4,
     'Compact Apple phone with flagship-class performance in a small body.', NULL),

    -- Apple tablets
    ('iPad Pro 12.9', 'Apple', 'tablet', 'iPadOS', '17.4', 'M2', 16,
     'Apple most powerful tablet, suitable for creative professionals.', NULL),
    ('iPad Air (5th Gen)', 'Apple', 'tablet', 'iPadOS', '17.0', 'M1', 8,
     'Versatile Apple tablet balancing performance and portability.', @carol),

    -- Samsung phones
    ('Galaxy S24 Ultra', 'Samsung', 'phone', 'Android', '14.0', 'Snapdragon 8 Gen 3', 12,
     'Samsung top-tier phone with S Pen and advanced AI camera features.', @dan),
    ('Galaxy S24', 'Samsung', 'phone', 'Android', '14.0', 'Snapdragon 8 Gen 3', 8,
     'Samsung flagship phone with a compact form factor.', NULL),
    ('Galaxy A54', 'Samsung', 'phone', 'Android', '14.0', 'Exynos 1380', 8,
     'Samsung mid-range phone offering solid performance at an accessible price.', @eva),
    ('Galaxy A14', 'Samsung', 'phone', 'Android', '13.0', 'Exynos 850', 4,
     'Entry-level Samsung phone designed for everyday tasks.', NULL),

    -- Samsung tablets
    ('Galaxy Tab S9 Ultra', 'Samsung', 'tablet', 'Android', '14.0', 'Snapdragon 8 Gen 2', 12,
     'Samsung largest tablet with an AMOLED display for productivity and media.', NULL),
    ('Galaxy Tab S9', 'Samsung', 'tablet', 'Android', '14.0', 'Snapdragon 8 Gen 2', 8,
     'Well-rounded Samsung tablet for business and entertainment use.', NULL),

    -- Google phones
    ('Pixel 8 Pro', 'Google', 'phone', 'Android', '14.0', 'Tensor G3', 12,
     'Google premium phone with computational photography and on-device AI.', NULL),
    ('Pixel 8', 'Google', 'phone', 'Android', '14.0', 'Tensor G3', 8,
     'Compact Google phone with clean Android and strong camera performance.', NULL),
    ('Pixel 7a', 'Google', 'phone', 'Android', '13.0', 'Tensor G2', 8,
     'Google mid-range phone delivering a pure Android experience.', NULL),

    -- OnePlus
    ('OnePlus 12', 'OnePlus', 'phone', 'Android', '14.0', 'Snapdragon 8 Gen 3', 16,
     'High-performance OnePlus phone with fast charging and a smooth display.', NULL);
END
GO